CREATE TABLE products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku_code TEXT NOT NULL,
    product_name TEXT NOT NULL,
    product_description TEXT,
    brand  TEXT NOT NULL,
    model  TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    unit_price REAL NOT NULL
);



INSERT INTO products (sku_code, product_name, product_description, brand, model, category, quantity_on_hand, unit_price) VALUES
('KEI00Q4K', 'Smartphones Item 1', 'The Apple iPhone 15 is a top-tier smartphones designed for premium performance and reliability.', 'Apple', 'iPhone 15', 'Smartphones', 34, 1433.29),
('P0KJN21V', 'Smartphones Item 2', 'The Samsung Galaxy S23 is a top-tier smartphones designed for premium performance and reliability.', 'Samsung', 'Galaxy S23', 'Smartphones', 80, 1446.0),
('JOASAMXH', 'Smartphones Item 3', 'The Google Pixel 8 is a top-tier smartphones designed for premium performance and reliability.', 'Google', 'Pixel 8', 'Smartphones', 40, 1267.44),
('DPVWH86R', 'Smartphones Item 4', 'The OnePlus 11 Pro is a top-tier smartphones designed for premium performance and reliability.', 'OnePlus', '11 Pro', 'Smartphones', 78, 1999.47),
('0731JTPV', 'Smartphones Item 5', 'The Xiaomi Mi 13 is a top-tier smartphones designed for premium performance and reliability.', 'Xiaomi', 'Mi 13', 'Smartphones', 43, 1651.99),
('7P5DGTTH', 'Laptops Item 6', 'The Dell XPS 13 is a top-tier laptops designed for premium performance and reliability.', 'Dell', 'XPS 13', 'Laptops', 97, 1593.38),
('IVFP3L1J', 'Laptops Item 7', 'The Apple MacBook Air M2 is a top-tier laptops designed for premium performance and reliability.', 'Apple', 'MacBook Air M2', 'Laptops', 30, 452.29),
('E577XUKY', 'Laptops Item 8', 'The HP Spectre x360 is a top-tier laptops designed for premium performance and reliability.', 'HP', 'Spectre x360', 'Laptops', 69, 1220.97),
('V1DDP6MR', 'Laptops Item 9', 'The Lenovo ThinkPad X1 is a top-tier laptops designed for premium performance and reliability.', 'Lenovo', 'ThinkPad X1', 'Laptops', 62, 1402.55),
('R5HEZKKW', 'Laptops Item 10', 'The Asus ZenBook 14 is a top-tier laptops designed for premium performance and reliability.', 'Asus', 'ZenBook 14', 'Laptops', 41, 1628.73),
('VPIRB850', 'Headphones Item 11', 'The Sony WH-1000XM5 is a top-tier headphones designed for premium performance and reliability.', 'Sony', 'WH-1000XM5', 'Headphones', 41, 1524.67),
('SAQ8ZOXG', 'Headphones Item 12', 'The Bose QC 45 is a top-tier headphones designed for premium performance and reliability.', 'Bose', 'QC 45', 'Headphones', 35, 1495.73),
('D254ZEGZ', 'Headphones Item 13', 'The Sennheiser Momentum 4 is a top-tier headphones designed for premium performance and reliability.', 'Sennheiser', 'Momentum 4', 'Headphones', 44, 1281.17),
('DGVD8ZEF', 'Headphones Item 14', 'The Apple AirPods Max is a top-tier headphones designed for premium performance and reliability.', 'Apple', 'AirPods Max', 'Headphones', 21, 583.42),
('BETF7ZY4', 'Headphones Item 15', 'The Jabra Elite 85h is a top-tier headphones designed for premium performance and reliability.', 'Jabra', 'Elite 85h', 'Headphones', 78, 160.27),
('ROURD40Z', 'Smartwatches Item 16', 'The Apple Watch Series 9 is a top-tier smartwatches designed for premium performance and reliability.', 'Apple', 'Watch Series 9', 'Smartwatches', 50, 1374.24),
('AY72M2O4', 'Smartwatches Item 17', 'The Samsung Galaxy Watch 6 is a top-tier smartwatches designed for premium performance and reliability.', 'Samsung', 'Galaxy Watch 6', 'Smartwatches', 96, 1680.61),
('L8XX97EE', 'Smartwatches Item 18', 'The Garmin Fenix 7 is a top-tier smartwatches designed for premium performance and reliability.', 'Garmin', 'Fenix 7', 'Smartwatches', 59, 1796.54),
('4ZDA4QTQ', 'Smartwatches Item 19', 'The Fitbit Versa 4 is a top-tier smartwatches designed for premium performance and reliability.', 'Fitbit', 'Versa 4', 'Smartwatches', 97, 1611.11),
('T08DA62J', 'Smartwatches Item 20', 'The Huawei Watch GT 4 is a top-tier smartwatches designed for premium performance and reliability.', 'Huawei', 'Watch GT 4', 'Smartwatches', 25, 1274.46),
('FT71V8XK', 'Televisions Item 21', 'The LG OLED C3 is a top-tier televisions designed for premium performance and reliability.', 'LG', 'OLED C3', 'Televisions', 80, 1936.97),
('D5QDZCQH', 'Televisions Item 22', 'The Samsung QLED Q90T is a top-tier televisions designed for premium performance and reliability.', 'Samsung', 'QLED Q90T', 'Televisions', 98, 848.15),
('217VKBP1', 'Televisions Item 23', 'The Sony Bravia XR is a top-tier televisions designed for premium performance and reliability.', 'Sony', 'Bravia XR', 'Televisions', 38, 473.5),
('0DS6CPHX', 'Televisions Item 24', 'The TCL 6-Series is a top-tier televisions designed for premium performance and reliability.', 'TCL', '6-Series', 'Televisions', 29, 52.4),
('0O18PPAL', 'Televisions Item 25', 'The Panasonic HZ2000 is a top-tier televisions designed for premium performance and reliability.', 'Panasonic', 'HZ2000', 'Televisions', 93, 384.96),
('SC6QQIFD', 'Cameras Item 26', 'The Canon EOS R5 is a top-tier cameras designed for premium performance and reliability.', 'Canon', 'EOS R5', 'Cameras', 45, 1954.03),
('FVNU10TN', 'Cameras Item 27', 'The Nikon Z7 II is a top-tier cameras designed for premium performance and reliability.', 'Nikon', 'Z7 II', 'Cameras', 47, 299.14),
('3H76J025', 'Cameras Item 28', 'The Sony Alpha A7 IV is a top-tier cameras designed for premium performance and reliability.', 'Sony', 'Alpha A7 IV', 'Cameras', 15, 1396.0),
('4OF4CT5S', 'Cameras Item 29', 'The Fujifilm X-T5 is a top-tier cameras designed for premium performance and reliability.', 'Fujifilm', 'X-T5', 'Cameras', 13, 898.89),
('BUFRVCA4', 'Cameras Item 30', 'The Panasonic Lumix S5 is a top-tier cameras designed for premium performance and reliability.', 'Panasonic', 'Lumix S5', 'Cameras', 46, 900.66),
('6ALCFLZS', 'Gaming Consoles Item 31', 'The Sony PlayStation 5 is a top-tier gaming consoles designed for premium performance and reliability.', 'Sony', 'PlayStation 5', 'Gaming', 35, 1474.41),
('GAAULJNX', 'Gaming Consoles Item 32', 'The Microsoft Xbox Series X is a top-tier gaming consoles designed for premium performance and reliability.', 'Microsoft', 'Xbox Series X', 'Gaming', 60, 1561.68),
('53187T69', 'Gaming Consoles Item 33', 'The Nintendo Switch OLED is a top-tier gaming consoles designed for premium performance and reliability.', 'Nintendo', 'Switch OLED', 'Gaming', 83, 1545.51),
('U4Y6UOYB', 'Gaming Consoles Item 34', 'The Valve Steam Deck is a top-tier gaming consoles designed for premium performance and reliability.', 'Valve', 'Steam Deck', 'Gaming', 47, 161.07),
('MWGD1V9Q', 'Gaming Consoles Item 35', 'The Logitech G Cloud is a top-tier gaming consoles designed for premium performance and reliability.', 'Logitech', 'G Cloud', 'Gaming', 47, 1741.51),
('TGWLTWVP', 'Kitchen Appliances Item 36', 'The Philips Airfryer XXL is a top-tier kitchen appliances designed for premium performance and reliability.', 'Philips', 'Airfryer XXL', 'Kitchen', 82, 1683.06),
('DOLNZ3NJ', 'Kitchen Appliances Item 37', 'The Panasonic Bread Maker SD is a top-tier kitchen appliances designed for premium performance and reliability.', 'Panasonic', 'Bread Maker SD', 'Kitchen', 99, 69.05),
('NEJ27E1S', 'Kitchen Appliances Item 38', 'The Breville Smart Oven Pro is a top-tier kitchen appliances designed for premium performance and reliability.', 'Breville', 'Smart Oven Pro', 'Kitchen', 24, 1046.49),
('YYHWMQGO', 'Kitchen Appliances Item 39', 'The KitchenAid Stand Mixer 5KSM is a top-tier kitchen appliances designed for premium performance and reliability.', 'KitchenAid', 'Stand Mixer 5KSM', 'Kitchen', 39, 217.04),
('CZPG6G3T', 'Kitchen Appliances Item 40', 'The Ninja Foodi Grill is a top-tier kitchen appliances designed for premium performance and reliability.', 'Ninja', 'Foodi Grill', 'Kitchen', 79, 1477.67),
('6Z47C16G', 'Fitness Equipment Item 41', 'The NordicTrack T Series Treadmill is a top-tier fitness equipment designed for premium performance and reliability.', 'NordicTrack', 'T Series Treadmill', 'Fitness', 41, 711.89),
('A29CTNRH', 'Fitness Equipment Item 42', 'The Bowflex SelectTech 552 is a top-tier fitness equipment designed for premium performance and reliability.', 'Bowflex', 'SelectTech 552', 'Fitness', 76, 520.79),
('77EHR2H9', 'Fitness Equipment Item 43', 'The Peloton Bike+ is a top-tier fitness equipment designed for premium performance and reliability.', 'Peloton', 'Bike+', 'Fitness', 89, 833.01),
('JIEUZKOI', 'Fitness Equipment Item 44', 'The ProForm HIIT Trainer is a top-tier fitness equipment designed for premium performance and reliability.', 'ProForm', 'HIIT Trainer', 'Fitness', 98, 1465.58),
('WFV6PPIO', 'Fitness Equipment Item 45', 'The Technogym MyRun is a top-tier fitness equipment designed for premium performance and reliability.', 'Technogym', 'MyRun', 'Fitness', 38, 136.57),
('8ABXXYTP', 'Books Item 46', 'The Penguin The Midnight Library is a top-tier books designed for premium performance and reliability.', 'Penguin', 'The Midnight Library', 'Books', 43, 960.98),
('XIRZQ00Z', 'Books Item 47', 'The HarperCollins Atomic Habits is a top-tier books designed for premium performance and reliability.', 'HarperCollins', 'Atomic Habits', 'Books', 82, 571.98),
('70YYT87L', 'Books Item 48', 'The Simon & Schuster The Psychology of Money is a top-tier books designed for premium performance and reliability.', 'Simon & Schuster', 'The Psychology of Money', 'Books', 30, 992.05),
('X3VQYEGN', 'Books Item 49', 'The Macmillan Project Hail Mary is a top-tier books designed for premium performance and reliability.', 'Macmillan', 'Project Hail Mary', 'Books', 61, 699.66),
('BLMBLZOZ', 'Books Item 50', 'The Bloomsbury Harry Potter Box Set is a top-tier books designed for premium performance and reliability.', 'Bloomsbury', 'Harry Potter Box Set', 'Books', 70, 310.48);
